package io.upit.dal;

/**
 * The Class UpitDAOException represents a general exception in the upit code base
 */
public class UpitDAOException extends RuntimeException {

    /** Auto-generated by eclipse. */
    private static final long serialVersionUID = -5455231428410510798L;

    /**
     * Instantiates a new UpitException.
     */
    public UpitDAOException() {
    }

    /**
     * Instantiates a new UpitDAOException.
     *
     * @param msg the msg
     */
    public UpitDAOException(String msg) {
        super(msg);
    }

    /**
     * Instantiates a new UpitDAOException.
     *
     * @param msg the msg
     * @param parent the parent
     */
    public UpitDAOException(String msg, Throwable parent) {
        super(msg, parent);
    }

}
